@startuml
'https://plantuml.com/class-diagram

package "Data Receiver"
{
    interface IDataReceiver{
        +dataIterator(): IFrameIterator?
    }

    class DataReceiver{
        -factory: IFrameIteratorFactory
        + DataReceiver(frameBuilder: IFrameIteratorFactory)
        +dataIterator(): IFrameIterator?
    }
}


package "Frame "
{
    interface IFrameIterator{
        +next(): IFrame
        +delay(): int
    }

    interface IFrame {
        +get(int width, int height): Pixel
    }

    interface IFrameIteratorFactory{
        +build(data: JSON)): IFrameIterator
    }

    class FrameIterator{
        -List[Frame]
        +next(): IFrame
        +delay(): int
    }

    class Frame{
        -pixes: List[Pixel]
        +get(int width, int height): Pixel
    }

    class FrameIteratorFactory{
        +build(data: JSON)): IFrameIterator
    }

    struct Pixel{
        +color: CRGB
        +brightness: int
    }
}

package "Matrix"
{
    class Matrix{
        +show(frame: IFrame)
    }
}

'---REL---'
IDataReceiver <|.. DataReceiver
DataReceiver o--left  IFrameIteratorFactory

IFrameIteratorFactory <|.. FrameIteratorFactory
FrameIteratorFactory -left..>  IFrameIterator: create

FrameIterator *--right IFrame

IFrameIterator <|.. FrameIterator

IFrame <|.. Frame
Frame *-- Pixel

Matrix -left....> IFrame: use
@enduml
