@startuml
'https://plantuml.com/class-diagram

package "Frame "
{
    interface IFrame {
        +get(int width, int height): Pixel
    }

    class Frame{
        -pixes: List[Pixel]
        +get(int width, int height): Pixel
    }

    class Pixel{
        +red(): int
        +green(): int
        +blue(): int
        +brightness(): int
    }
}

package "Iterator"
{
    interface IConnection{
        +data(): JSON?
    }

    interface IDataIterator{
        +next(): IFrame
        +delay(): int
    }

    class DataIterator{
        -frames: List[Frame]
        -count: size_t
        -current: size_t
        +DataIterator(connection: IConnection)
        +next(): IFrame
        +delay(): int
        -json_to_frames(data:JSON): List[Frame]
    }

    class BluetoothConnection{
        +data(): JSON?
    }
}



package "Matrix "
{
    interface IMatrix{
        +show(frame: IFrame)
    }

    class Matrix{
        +show(frame: IFrame)
    }
}

package "Main" <<NODE>>
{

}

'---REL---'

IFrame <|.. Frame
Frame o-- Pixel

IMatrix -down..> IFrame: use
IMatrix <|.. Matrix

IDataIterator -left..> IFrame: create
IConnection <|.. BluetoothConnection
IDataIterator <|.. DataIterator
DataIterator o--left IConnection

"Main" <--[thickness=3]- IDataIterator
"Main" <--[thickness=3]right IMatrix

@enduml
